"""Initial schema multitenant

Revision ID: 90cda887a999
Revises: 
Create Date: 2026-03-10 01:55:10.618856-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90cda887a999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('severidad', sa.Float(), nullable=True),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('pais', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('coordenadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fuente', sa.String(length=64), nullable=True),
    sa.Column('datos_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('procesada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alertas_fecha', 'alertas', ['created_at'], unique=False)
    op.create_index('idx_alertas_severidad', 'alertas', ['severidad'], unique=False)
    op.create_index(op.f('ix_alertas_pais'), 'alertas', ['pais'], unique=False)
    op.create_index(op.f('ix_alertas_tipo'), 'alertas', ['tipo'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_cal_event')
    )
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('cognitive_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_style', sa.String(length=32), nullable=True),
    sa.Column('vocabulary', sa.String(length=32), nullable=True),
    sa.Column('content_length', sa.String(length=32), nullable=True),
    sa.Column('tone', sa.String(length=32), nullable=True),
    sa.Column('presentation', sa.String(length=32), nullable=True),
    sa.Column('sequence', sa.String(length=32), nullable=True),
    sa.Column('depth_level', sa.String(length=32), nullable=True),
    sa.Column('example_mode', sa.String(length=32), nullable=True),
    sa.Column('format_pref', sa.String(length=32), nullable=True),
    sa.Column('expertise', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_profile_user_id'), 'cognitive_profile', ['user_id'], unique=True)
    op.create_table('consultas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversacion_id', sa.UUID(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('contexto_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consultas_fecha', 'consultas', ['created_at'], unique=False)
    op.create_index('idx_consultas_user', 'consultas', ['user_id'], unique=False)
    op.create_index(op.f('ix_consultas_conversacion_id'), 'consultas', ['conversacion_id'], unique=False)
    op.create_index(op.f('ix_consultas_user_id'), 'consultas', ['user_id'], unique=False)
    op.create_table('conversaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_user_id'), 'conversaciones', ['user_id'], unique=False)
    op.create_table('costos_api',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('modelo', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('operacion', sa.String(length=64), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_costos_fecha_modelo', 'costos_api', ['fecha', 'modelo'], unique=False)
    op.create_index(op.f('ix_costos_api_fecha'), 'costos_api', ['fecha'], unique=False)
    op.create_table('email_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_status'), 'email_queue', ['status'], unique=False)
    op.create_index(op.f('ix_email_queue_user_id'), 'email_queue', ['user_id'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vectorizado', sa.Boolean(), nullable=True),
    sa.Column('vectorizado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qdrant_id', sa.String(length=128), nullable=True),
    sa.Column('qdrant_collection', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidencia_created', 'evidencia', ['created_at'], unique=False)
    op.create_index('idx_evidencia_tipo', 'evidencia', ['file_type'], unique=False)
    op.create_index(op.f('ix_evidencia_content_hash'), 'evidencia', ['content_hash'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('regions_of_interest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), nullable=True),
    sa.Column('realtime_alerts', sa.Boolean(), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('oauth_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_user_provider')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_tokens_dia', sa.Integer(), nullable=True),
    sa.Column('max_storage_mb', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('vectorizados_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evidencia_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('chunks_total', sa.Integer(), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('modelo_embed', sa.String(length=64), nullable=True),
    sa.Column('duracion_seg', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectorizados_log_evidencia_id'), 'vectorizados_log', ['evidencia_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mensajes_conv_fecha', 'mensajes', ['conversacion_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    # op.drop_table('ci_logs')
    # op.drop_table('alerts')
    # op.drop_table('ci_setup')
    # op.drop_table('alembic_version')
    # op.drop_index(op.f('nexo_documentos_embedding_idx'), table_name='nexo_documentos', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.drop_table('nexo_documentos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nexo_documentos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('hash_sha256', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nexo_documentos_pkey')),
    sa.UniqueConstraint('hash_sha256', name=op.f('nexo_documentos_hash_sha256_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('nexo_documentos_embedding_idx'), 'nexo_documentos', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('ci_setup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ci_setup_pkey'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('level', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_table('ci_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('ci_setup_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ci_setup_id'], ['ci_setup.id'], name=op.f('ci_logs_ci_setup_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ci_logs_pkey'))
    )
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index('idx_sessions_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_mensajes_conv_fecha', table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_vectorizados_log_evidencia_id'), table_name='vectorizados_log')
    op.drop_table('vectorizados_log')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_evidencia_content_hash'), table_name='evidencia')
    op.drop_index('idx_evidencia_tipo', table_name='evidencia')
    op.drop_index('idx_evidencia_created', table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_email_queue_user_id'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_status'), table_name='email_queue')
    op.drop_table('email_queue')
    op.drop_index(op.f('ix_costos_api_fecha'), table_name='costos_api')
    op.drop_index('idx_costos_fecha_modelo', table_name='costos_api')
    op.drop_table('costos_api')
    op.drop_index(op.f('ix_conversaciones_user_id'), table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_index(op.f('ix_consultas_user_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_conversacion_id'), table_name='consultas')
    op.drop_index('idx_consultas_user', table_name='consultas')
    op.drop_index('idx_consultas_fecha', table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_cognitive_profile_user_id'), table_name='cognitive_profile')
    op.drop_table('cognitive_profile')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_alertas_tipo'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_pais'), table_name='alertas')
    op.drop_index('idx_alertas_severidad', table_name='alertas')
    op.drop_index('idx_alertas_fecha', table_name='alertas')
    op.drop_table('alertas')
    # ### end Alembic commands ###
