import json
import logging
from core.config import settings
from core.system_config import get_config, update_config
from core.learning_log import log_change
try:
    from openai import AsyncAzureOpenAI
except ImportError:
    AsyncAzureOpenAI = None

logger = logging.getLogger(__name__)

class AIController:
    def __init__(self):
        self.client = None
        if AsyncAzureOpenAI and settings.AZURE_OPENAI_KEY:
            self.client = AsyncAzureOpenAI(
                api_key=settings.AZURE_OPENAI_KEY,
                api_version="2023-12-01-preview",
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT
            )

    async def execute_command(self, command: str) -> dict:
        """Traduce comandos de lenguaje natural a mutaciones del runtime del sistema."""
        logger.info(f"🧠 [AI CONTROLLER] Procesando directiva de usuario: '{command}'")
        current_config = get_config()
        
        if not self.client:
            logger.warning("No hay acceso a Azure OpenAI. Imposible mutar sistema por NLP.")
            return {"action": "error", "error": "Azure OpenAI no configurado.", "config": current_config}

        prompt = (
            "You are the Core System Control AI of NEXO SOBERANO. Your job is to mutate the dynamic configuration of the intelligence platform based on user natural language commands.\n"
            "Given the user's command and the current configuration state, return a NEW completely valid JSON object representing the entire updated configuration.\n"
            "Current Config State:\n"
            f"{json.dumps(current_config, indent=2)}\n\n"
            "Rules & Heuristics:\n"
            "- If user says 'aggressive videos' -> change video.style to 'aggressive'.\n"
            "- If user says 'neutral videos' -> change video.style to 'neutral'.\n"
            "- If user says 'lower AI costs' or 'be cheaper' -> reduce ai.temperature and lower ai.max_tokens.\n"
            "- If user says 'process more videos' or 'make videos for everything' -> lower video.min_impact_score to 5 or 6.\n"
            "- If user says 'critical videos only' -> raise video.min_impact_score to 9.\n"
            "If the command is unintelligible or empty, return the exact current config untouched.\n"
            "Return ONLY the raw JSON format with no markdown wrappers."
        )

        try:
            response = await self.client.chat.completions.create(
                model=settings.AZURE_OPENAI_DEPLOYMENT,
                messages=[
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": f"Command: {command}"}
                ],
                temperature=0.1, # Muy determinista
                response_format={"type": "json_object"}
            )
            
            raw_content = response.choices[0].message.content
            new_config = json.loads(raw_content)
            
            # Registrar evolución en el Learning Log
            log_change("nlp_mutation", current_config, new_config, command)
            
            update_config(new_config)
            logger.info("✅ [AI CONTROLLER] Directiva NLP aplicada! Pipeline re-rutado dinámicamente.")
            
            return {
                "action": "system_mutated",
                "command_interpreted": command,
                "previous_config": current_config,
                "current_config": new_config
            }
            
        except json.JSONDecodeError as e:
            logger.error(f"Falla parseando el JSON mutado del AI Controller: {e}")
            return {"action": "error", "error": "Invalid JSON generated by Controller", "config": current_config}
        except Exception as e:
            logger.error(f"Error fatal interpretando comando de sistema: {e}")
            return {"action": "error", "error": str(e), "config": current_config}

ai_controller = AIController()
